[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
env = { COREPACK_ENABLE_DOWNLOADS = "1" }
cmds = [
  "npm i -g corepack@0.24.1 && corepack enable",
  "corepack prepare pnpm@9.12.3 --activate",
  "pnpm -w install --frozen-lockfile"
]

[phases.build]
cmds = ["pnpm -w --filter web build"]

[start]
cmd = "pnpm -w --filter web start"
