[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm i -g corepack@0.24.1 && corepack enable",
  "pnpm -w install --frozen-lockfile"
]

[phases.build]
cmds = ["pnpm -w --filter web build"]

[start]
cmd = "pnpm -w --filter web start"
