[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
# Install pnpm via corepack, then install deps from the workspace root
cmds = [
  "npm i -g corepack@0.24.1 && corepack enable",
  "pnpm -w install --frozen-lockfile"
]

[phases.build]
# Build only the API package
cmds = ["pnpm -w --filter api build"]

[start]
# Start only the API package
cmd = "pnpm -w --filter api start"
